using System.Threading.Tasks;

namespace PlaywrightSharp
{
    /// <summary>
    /// Coverage gathers information about parts of JavaScript and CSS that were used by the page.
    /// </summary>
    /// <seealso cref="IPage.Coverage"/>
    public interface ICoverage
    {
        /// <summary>
        /// Starts the JS coverage.
        /// </summary>
        /// <param name="resetOnNavigation">Whether to reset coverage on every navigation. Defaults to <c>true</c>.</param>
        /// <param name="reportAnonymousScripts">Whether anonymous scripts generated by the page should be reported. Defaults to <c>false</c>.</param>
        /// <returns>A <see cref="Task"/> that completes when the message was confirmed by the browser.</returns>
        Task StartJSCoverageAsync(bool resetOnNavigation = true, bool reportAnonymousScripts = false);

        /// <summary>
        /// Stops the JS coverage.
        /// </summary>
        /// <returns>A <see cref="Task"/> that completes when the message was confirmed by the browser, yielding the coverage result.</returns>
        Task<JSCoverageEntry[]> StopJSCoverageAsync();

        /// <summary>
        /// Starts CSS coverage.
        /// </summary>
        /// <param name="resetOnNavigation">Whether to reset coverage on every navigation. Defaults to <c>true</c>.</param>
        /// <returns>A task that resolves when coverage is started.</returns>
        Task StartCSSCoverageAsync(bool resetOnNavigation = true);

        /// <summary>
        /// Stops JS coverage and returns coverage reports for all non-anonymous scripts.
        /// </summary>
        /// <returns>Task that resolves to the array of coverage reports for all stylesheets.</returns>
        /// <remarks>
        /// JavaScript Coverage doesn't include anonymous scripts; however, scripts with sourceURLs are reported.
        /// </remarks>
        public Task<CSSCoverageEntry[]> StopCSSCoverageAsync();
    }
}
