/*
 * MIT License
 *
 * Copyright (c) Microsoft Corporation.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Microsoft.Playwright.Transport.Converters;
using Microsoft.Playwright.Transport.Protocol;

namespace Microsoft.Playwright.Transport;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    Converters = [typeof(AotEnumMemberConverter)])]
[JsonSerializable(typeof(PlaywrightServerMessage))]
[JsonSerializable(typeof(ErrorEntry))]
[JsonSerializable(typeof(PlaywrightServerError))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(Dictionary<string, object?>), TypeInfoPropertyName = "DictionaryOfStringToObject")]
[JsonSerializable(typeof(List<Dictionary<string, object?>>), TypeInfoPropertyName = "ListOfDictionaryStringToObject")]
[JsonSerializable(typeof(List<object?>), TypeInfoPropertyName = "ListOfObject")]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(decimal?))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(Guid?))]
[JsonSerializable(typeof(byte[]))]
[JsonSerializable(typeof(sbyte[]))]
[JsonSerializable(typeof(short[]))]
[JsonSerializable(typeof(ushort[]))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(uint[]))]
[JsonSerializable(typeof(long[]))]
[JsonSerializable(typeof(ulong[]))]
[JsonSerializable(typeof(float[]))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(int[][]))]
[JsonSerializable(typeof(uint[][]))]
[JsonSerializable(typeof(string[][]))]
[JsonSerializable(typeof(System.Numerics.BigInteger))]
[JsonSerializable(typeof(System.Text.Json.JsonDocument))]
[JsonSerializable(typeof(System.Uri))]
[JsonSerializable(typeof(System.DateTime))]
[JsonSerializable(typeof(System.DateTime?))]
[JsonSerializable(typeof(JsonObject))]
[JsonSerializable(typeof(JsonArray))]
[JsonSerializable(typeof(JsonValue))]
[JsonSerializable(typeof(JsonNode))]
[JsonSerializable(typeof(System.Text.Json.JsonElement))]
[JsonSerializable(typeof(KeyJsonElementValueObject))]
[JsonSerializable(typeof(KeyJsonElementValueObject[]))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(BrowserBindResult))]
[JsonSerializable(typeof(ClientCertificate))]
[JsonSerializable(typeof(ClientCertificate[]))]
[JsonSerializable(typeof(List<ClientCertificate>), TypeInfoPropertyName = "ListOfClientCertificate")]
[JsonSerializable(typeof(Clip))]
[JsonSerializable(typeof(Cookie))]
[JsonSerializable(typeof(Cookie[]))]
[JsonSerializable(typeof(List<Cookie>), TypeInfoPropertyName = "ListOfCookie")]
[JsonSerializable(typeof(DropPayload))]
[JsonSerializable(typeof(FilePayload))]
[JsonSerializable(typeof(FilePayload[]))]
[JsonSerializable(typeof(List<FilePayload>), TypeInfoPropertyName = "ListOfFilePayload")]
[JsonSerializable(typeof(Geolocation))]
[JsonSerializable(typeof(Header))]
[JsonSerializable(typeof(Header[]))]
[JsonSerializable(typeof(List<Header>), TypeInfoPropertyName = "ListOfHeader")]
[JsonSerializable(typeof(HttpCredentials))]
[JsonSerializable(typeof(Location))]
[JsonSerializable(typeof(LocatorBoundingBoxResult))]
[JsonSerializable(typeof(Margin))]
[JsonSerializable(typeof(PageViewportSizeResult))]
[JsonSerializable(typeof(Position))]
[JsonSerializable(typeof(Proxy))]
[JsonSerializable(typeof(RecordVideoSize))]
[JsonSerializable(typeof(RequestTimingResult))]
[JsonSerializable(typeof(ScreenSize))]
[JsonSerializable(typeof(ScreencastSize))]
[JsonSerializable(typeof(SelectOptionValue))]
[JsonSerializable(typeof(SelectOptionValue[]))]
[JsonSerializable(typeof(List<SelectOptionValue>), TypeInfoPropertyName = "ListOfSelectOptionValue")]
[JsonSerializable(typeof(SourcePosition))]
[JsonSerializable(typeof(TargetPosition))]
[JsonSerializable(typeof(ViewportSize))]
[JsonSerializable(typeof(ScreencastFrame))]
[JsonSerializable(typeof(BrowserContextCookiesResult))]
[JsonSerializable(typeof(ResponseSecurityDetailsResult))]
[JsonSerializable(typeof(ResponseServerAddrResult))]
[JsonSerializable(typeof(RequestSizesResult))]
[JsonSerializable(typeof(WebErrorLocation))]
[JsonSerializable(typeof(ElementHandleBoundingBoxResult))]
[JsonSerializable(typeof(Core.ConsoleMessageInitializer))]
[JsonSerializable(typeof(Core.FrameNavigatedEventArgs))]
[JsonSerializable(typeof(Core.NavigateDocument))]
[JsonSerializable(typeof(Core.JSElementProperty))]
[JsonSerializable(typeof(DebuggerPausedDetails))]
[JsonSerializable(typeof(WebStorageItem))]
[JsonSerializable(typeof(List<Core.ConsoleMessageInitializer>), TypeInfoPropertyName = "ListOfConsoleMessageInitializer")]
[JsonSerializable(typeof(List<Core.JSElementProperty>), TypeInfoPropertyName = "ListOfJSElementProperty")]
[JsonSerializable(typeof(List<NameValue>), TypeInfoPropertyName = "ListOfNameValue")]
[JsonSerializable(typeof(List<SerializedError>), TypeInfoPropertyName = "ListOfSerializedError")]
[JsonSerializable(typeof(List<VirtualCredential>), TypeInfoPropertyName = "ListOfVirtualCredential")]
[JsonSerializable(typeof(List<WebStorageItem>), TypeInfoPropertyName = "ListOfWebStorageItem")]
[JsonSerializable(typeof(IReadOnlyList<BrowserContextCookiesResult>), TypeInfoPropertyName = "IReadOnlyListOfBrowserContextCookiesResult")]
[JsonSerializable(typeof(Channels.BrowserContextChannelRequestEventArgs))]
[JsonSerializable(typeof(Channels.BrowserContextChannelResponseEventArgs))]
[JsonSerializable(typeof(RequestSizesResult))]
// Protocol initializer types (68 types)
[JsonSerializable(typeof(AndroidDeviceInitializer))]
[JsonSerializable(typeof(AndroidElementInfo))]
[JsonSerializable(typeof(AndroidInitializer))]
[JsonSerializable(typeof(AndroidSelector))]
[JsonSerializable(typeof(AndroidSelectorHasChild))]
[JsonSerializable(typeof(AndroidSelectorHasDescendant))]
[JsonSerializable(typeof(AndroidSocketInitializer))]
[JsonSerializable(typeof(AndroidWebView))]
[JsonSerializable(typeof(APIRequestContextInitializer))]
[JsonSerializable(typeof(APIResponse))]
[JsonSerializable(typeof(ArtifactInitializer))]
[JsonSerializable(typeof(BindingCallInitializer))]
[JsonSerializable(typeof(BrowserContextInitializer))]
[JsonSerializable(typeof(BrowserInitializer))]
[JsonSerializable(typeof(BrowserTypeInitializer))]
[JsonSerializable(typeof(CDPSessionInitializer))]
[JsonSerializable(typeof(ClientSideCallMetadata))]
[JsonSerializable(typeof(DebugControllerInitializer))]
[JsonSerializable(typeof(DebuggerInitializer))]
[JsonSerializable(typeof(DialogInitializer))]
[JsonSerializable(typeof(DisposableInitializer))]
[JsonSerializable(typeof(ElectronApplicationInitializer))]
[JsonSerializable(typeof(ElectronInitializer))]
[JsonSerializable(typeof(ElementHandleInitializer))]
[JsonSerializable(typeof(ExpectedTextValue))]
[JsonSerializable(typeof(FormField))]
[JsonSerializable(typeof(FormFieldFile))]
[JsonSerializable(typeof(FrameInitializer))]
[JsonSerializable(typeof(JSHandleInitializer))]
[JsonSerializable(typeof(JsonPipeInitializer))]
[JsonSerializable(typeof(LocalUtilsInitializer))]
[JsonSerializable(typeof(Metadata))]
[JsonSerializable(typeof(MetadataLocation))]
[JsonSerializable(typeof(NameValue))]
[JsonSerializable(typeof(PageInitializer))]
[JsonSerializable(typeof(PlaywrightInitializer))]
[JsonSerializable(typeof(Point))]
[JsonSerializable(typeof(RecorderSource))]
[JsonSerializable(typeof(RecorderSourceHighlight))]
[JsonSerializable(typeof(RecordHarOptions))]
[JsonSerializable(typeof(Rect))]
[JsonSerializable(typeof(RemoteAddr))]
[JsonSerializable(typeof(RequestInitializer))]
[JsonSerializable(typeof(RequestSizes))]
[JsonSerializable(typeof(ResourceTiming))]
[JsonSerializable(typeof(ResponseInitializer))]
[JsonSerializable(typeof(RootInitializer))]
[JsonSerializable(typeof(RouteInitializer))]
[JsonSerializable(typeof(SecurityDetails))]
[JsonSerializable(typeof(SelectorEngine))]
[JsonSerializable(typeof(SerializedError))]
[JsonSerializable(typeof(SerializedErrorError))]
[JsonSerializable(typeof(SerializedValue))]
[JsonSerializable(typeof(SerializedValueE))]
[JsonSerializable(typeof(SerializedValueO))]
[JsonSerializable(typeof(SerializedValueR))]
[JsonSerializable(typeof(SerializedValueTa))]
[JsonSerializable(typeof(SocksSupportInitializer))]
[JsonSerializable(typeof(StackFrame))]
[JsonSerializable(typeof(StreamInitializer))]
[JsonSerializable(typeof(TracingInitializer))]
[JsonSerializable(typeof(URLPattern))]
[JsonSerializable(typeof(VirtualCredential))]
[JsonSerializable(typeof(WaitInfo))]
[JsonSerializable(typeof(WebSocketInitializer))]
[JsonSerializable(typeof(WebSocketRouteInitializer))]
[JsonSerializable(typeof(WorkerInitializer))]
[JsonSerializable(typeof(WritableStreamInitializer))]
// Generated option types (272 types)
[JsonSerializable(typeof(APIRequestContextOptions))]
[JsonSerializable(typeof(APIRequestContextStorageStateOptions))]
[JsonSerializable(typeof(APIRequestNewContextOptions))]
[JsonSerializable(typeof(BrowserBindOptions))]
[JsonSerializable(typeof(BrowserCloseOptions))]
[JsonSerializable(typeof(BrowserContextClearCookiesOptions))]
[JsonSerializable(typeof(BrowserContextCloseOptions))]
[JsonSerializable(typeof(BrowserContextGrantPermissionsOptions))]
[JsonSerializable(typeof(BrowserContextRouteFromHAROptions))]
[JsonSerializable(typeof(BrowserContextRouteOptions))]
[JsonSerializable(typeof(BrowserContextRunAndWaitForConsoleMessageOptions))]
[JsonSerializable(typeof(BrowserContextRunAndWaitForPageOptions))]
[JsonSerializable(typeof(BrowserContextStorageStateOptions))]
[JsonSerializable(typeof(BrowserContextUnrouteAllOptions))]
[JsonSerializable(typeof(BrowserContextWaitForConsoleMessageOptions))]
[JsonSerializable(typeof(BrowserContextWaitForPageOptions))]
[JsonSerializable(typeof(BrowserNewContextOptions))]
[JsonSerializable(typeof(BrowserNewPageOptions))]
[JsonSerializable(typeof(BrowserTypeConnectOptions))]
[JsonSerializable(typeof(BrowserTypeConnectOverCDPOptions))]
[JsonSerializable(typeof(BrowserTypeLaunchOptions))]
[JsonSerializable(typeof(BrowserTypeLaunchPersistentContextOptions))]
[JsonSerializable(typeof(ClockInstallOptions))]
[JsonSerializable(typeof(CredentialsCreateOptions))]
[JsonSerializable(typeof(CredentialsGetOptions))]
[JsonSerializable(typeof(ElementHandleCheckOptions))]
[JsonSerializable(typeof(ElementHandleClickOptions))]
[JsonSerializable(typeof(ElementHandleDblClickOptions))]
[JsonSerializable(typeof(ElementHandleFillOptions))]
[JsonSerializable(typeof(ElementHandleHoverOptions))]
[JsonSerializable(typeof(ElementHandleInputValueOptions))]
[JsonSerializable(typeof(ElementHandlePressOptions))]
[JsonSerializable(typeof(ElementHandleScreenshotOptions))]
[JsonSerializable(typeof(ElementHandleScrollIntoViewIfNeededOptions))]
[JsonSerializable(typeof(ElementHandleSelectOptionOptions))]
[JsonSerializable(typeof(ElementHandleSelectTextOptions))]
[JsonSerializable(typeof(ElementHandleSetCheckedOptions))]
[JsonSerializable(typeof(ElementHandleSetInputFilesOptions))]
[JsonSerializable(typeof(ElementHandleTapOptions))]
[JsonSerializable(typeof(ElementHandleTypeOptions))]
[JsonSerializable(typeof(ElementHandleUncheckOptions))]
[JsonSerializable(typeof(ElementHandleWaitForElementStateOptions))]
[JsonSerializable(typeof(ElementHandleWaitForSelectorOptions))]
[JsonSerializable(typeof(FileChooserSetFilesOptions))]
[JsonSerializable(typeof(FrameAddScriptTagOptions))]
[JsonSerializable(typeof(FrameAddStyleTagOptions))]
[JsonSerializable(typeof(FrameCheckOptions))]
[JsonSerializable(typeof(FrameClickOptions))]
[JsonSerializable(typeof(FrameDblClickOptions))]
[JsonSerializable(typeof(FrameDispatchEventOptions))]
[JsonSerializable(typeof(FrameDragAndDropOptions))]
[JsonSerializable(typeof(FrameEvalOnSelectorOptions))]
[JsonSerializable(typeof(FrameFillOptions))]
[JsonSerializable(typeof(FrameFocusOptions))]
[JsonSerializable(typeof(FrameGetAttributeOptions))]
[JsonSerializable(typeof(FrameGetByAltTextOptions))]
[JsonSerializable(typeof(FrameGetByLabelOptions))]
[JsonSerializable(typeof(FrameGetByPlaceholderOptions))]
[JsonSerializable(typeof(FrameGetByRoleOptions))]
[JsonSerializable(typeof(FrameGetByTextOptions))]
[JsonSerializable(typeof(FrameGetByTitleOptions))]
[JsonSerializable(typeof(FrameGotoOptions))]
[JsonSerializable(typeof(FrameHoverOptions))]
[JsonSerializable(typeof(FrameInnerHTMLOptions))]
[JsonSerializable(typeof(FrameInnerTextOptions))]
[JsonSerializable(typeof(FrameInputValueOptions))]
[JsonSerializable(typeof(FrameIsCheckedOptions))]
[JsonSerializable(typeof(FrameIsDisabledOptions))]
[JsonSerializable(typeof(FrameIsEditableOptions))]
[JsonSerializable(typeof(FrameIsEnabledOptions))]
[JsonSerializable(typeof(FrameIsHiddenOptions))]
[JsonSerializable(typeof(FrameIsVisibleOptions))]
[JsonSerializable(typeof(FrameLocatorGetByAltTextOptions))]
[JsonSerializable(typeof(FrameLocatorGetByLabelOptions))]
[JsonSerializable(typeof(FrameLocatorGetByPlaceholderOptions))]
[JsonSerializable(typeof(FrameLocatorGetByRoleOptions))]
[JsonSerializable(typeof(FrameLocatorGetByTextOptions))]
[JsonSerializable(typeof(FrameLocatorGetByTitleOptions))]
[JsonSerializable(typeof(FrameLocatorLocatorOptions))]
[JsonSerializable(typeof(FrameLocatorOptions))]
[JsonSerializable(typeof(FramePressOptions))]
[JsonSerializable(typeof(FrameQuerySelectorOptions))]
[JsonSerializable(typeof(FrameRunAndWaitForNavigationOptions))]
[JsonSerializable(typeof(FrameSelectOptionOptions))]
[JsonSerializable(typeof(FrameSetCheckedOptions))]
[JsonSerializable(typeof(FrameSetContentOptions))]
[JsonSerializable(typeof(FrameSetInputFilesOptions))]
[JsonSerializable(typeof(FrameTapOptions))]
[JsonSerializable(typeof(FrameTextContentOptions))]
[JsonSerializable(typeof(FrameTypeOptions))]
[JsonSerializable(typeof(FrameUncheckOptions))]
[JsonSerializable(typeof(FrameWaitForFunctionOptions))]
[JsonSerializable(typeof(FrameWaitForLoadStateOptions))]
[JsonSerializable(typeof(FrameWaitForNavigationOptions))]
[JsonSerializable(typeof(FrameWaitForSelectorOptions))]
[JsonSerializable(typeof(FrameWaitForURLOptions))]
[JsonSerializable(typeof(KeyboardPressOptions))]
[JsonSerializable(typeof(KeyboardTypeOptions))]
[JsonSerializable(typeof(LocatorAriaSnapshotOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeAttachedOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeCheckedOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeDisabledOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeEditableOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeEmptyOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeEnabledOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeFocusedOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeHiddenOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeInViewportOptions))]
[JsonSerializable(typeof(LocatorAssertionsToBeVisibleOptions))]
[JsonSerializable(typeof(LocatorAssertionsToContainClassOptions))]
[JsonSerializable(typeof(LocatorAssertionsToContainTextOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveAccessibleDescriptionOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveAccessibleErrorMessageOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveAccessibleNameOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveAttributeOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveClassOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveCountOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveCSSOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveIdOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveJSPropertyOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveRoleOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveTextOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveValueOptions))]
[JsonSerializable(typeof(LocatorAssertionsToHaveValuesOptions))]
[JsonSerializable(typeof(LocatorAssertionsToMatchAriaSnapshotOptions))]
[JsonSerializable(typeof(LocatorBlurOptions))]
[JsonSerializable(typeof(LocatorBoundingBoxOptions))]
[JsonSerializable(typeof(LocatorCheckOptions))]
[JsonSerializable(typeof(LocatorClearOptions))]
[JsonSerializable(typeof(LocatorClickOptions))]
[JsonSerializable(typeof(LocatorDblClickOptions))]
[JsonSerializable(typeof(LocatorDispatchEventOptions))]
[JsonSerializable(typeof(LocatorDragToOptions))]
[JsonSerializable(typeof(LocatorDropOptions))]
[JsonSerializable(typeof(LocatorElementHandleOptions))]
[JsonSerializable(typeof(LocatorEvaluateHandleOptions))]
[JsonSerializable(typeof(LocatorEvaluateOptions))]
[JsonSerializable(typeof(LocatorFillOptions))]
[JsonSerializable(typeof(LocatorFilterOptions))]
[JsonSerializable(typeof(LocatorFocusOptions))]
[JsonSerializable(typeof(LocatorGetAttributeOptions))]
[JsonSerializable(typeof(LocatorGetByAltTextOptions))]
[JsonSerializable(typeof(LocatorGetByLabelOptions))]
[JsonSerializable(typeof(LocatorGetByPlaceholderOptions))]
[JsonSerializable(typeof(LocatorGetByRoleOptions))]
[JsonSerializable(typeof(LocatorGetByTextOptions))]
[JsonSerializable(typeof(LocatorGetByTitleOptions))]
[JsonSerializable(typeof(LocatorHighlightOptions))]
[JsonSerializable(typeof(LocatorHoverOptions))]
[JsonSerializable(typeof(LocatorInnerHTMLOptions))]
[JsonSerializable(typeof(LocatorInnerTextOptions))]
[JsonSerializable(typeof(LocatorInputValueOptions))]
[JsonSerializable(typeof(LocatorIsCheckedOptions))]
[JsonSerializable(typeof(LocatorIsDisabledOptions))]
[JsonSerializable(typeof(LocatorIsEditableOptions))]
[JsonSerializable(typeof(LocatorIsEnabledOptions))]
[JsonSerializable(typeof(LocatorIsHiddenOptions))]
[JsonSerializable(typeof(LocatorIsVisibleOptions))]
[JsonSerializable(typeof(LocatorLocatorOptions))]
[JsonSerializable(typeof(LocatorPressOptions))]
[JsonSerializable(typeof(LocatorPressSequentiallyOptions))]
[JsonSerializable(typeof(LocatorScreenshotOptions))]
[JsonSerializable(typeof(LocatorScrollIntoViewIfNeededOptions))]
[JsonSerializable(typeof(LocatorSelectOptionOptions))]
[JsonSerializable(typeof(LocatorSelectTextOptions))]
[JsonSerializable(typeof(LocatorSetCheckedOptions))]
[JsonSerializable(typeof(LocatorSetInputFilesOptions))]
[JsonSerializable(typeof(LocatorTapOptions))]
[JsonSerializable(typeof(LocatorTextContentOptions))]
[JsonSerializable(typeof(LocatorTypeOptions))]
[JsonSerializable(typeof(LocatorUncheckOptions))]
[JsonSerializable(typeof(LocatorWaitForOptions))]
[JsonSerializable(typeof(MouseClickOptions))]
[JsonSerializable(typeof(MouseDblClickOptions))]
[JsonSerializable(typeof(MouseDownOptions))]
[JsonSerializable(typeof(MouseMoveOptions))]
[JsonSerializable(typeof(MouseUpOptions))]
[JsonSerializable(typeof(PageAddLocatorHandlerOptions))]
[JsonSerializable(typeof(PageAddScriptTagOptions))]
[JsonSerializable(typeof(PageAddStyleTagOptions))]
[JsonSerializable(typeof(PageAriaSnapshotOptions))]
[JsonSerializable(typeof(PageAssertionsToHaveTitleOptions))]
[JsonSerializable(typeof(PageAssertionsToHaveURLOptions))]
[JsonSerializable(typeof(PageAssertionsToMatchAriaSnapshotOptions))]
[JsonSerializable(typeof(PageCheckOptions))]
[JsonSerializable(typeof(PageClickOptions))]
[JsonSerializable(typeof(PageCloseOptions))]
[JsonSerializable(typeof(PageConsoleMessagesOptions))]
[JsonSerializable(typeof(PageDblClickOptions))]
[JsonSerializable(typeof(PageDispatchEventOptions))]
[JsonSerializable(typeof(PageDragAndDropOptions))]
[JsonSerializable(typeof(PageEmulateMediaOptions))]
[JsonSerializable(typeof(PageEvalOnSelectorOptions))]
[JsonSerializable(typeof(PageFillOptions))]
[JsonSerializable(typeof(PageFocusOptions))]
[JsonSerializable(typeof(PageGetAttributeOptions))]
[JsonSerializable(typeof(PageGetByAltTextOptions))]
[JsonSerializable(typeof(PageGetByLabelOptions))]
[JsonSerializable(typeof(PageGetByPlaceholderOptions))]
[JsonSerializable(typeof(PageGetByRoleOptions))]
[JsonSerializable(typeof(PageGetByTextOptions))]
[JsonSerializable(typeof(PageGetByTitleOptions))]
[JsonSerializable(typeof(PageGoBackOptions))]
[JsonSerializable(typeof(PageGoForwardOptions))]
[JsonSerializable(typeof(PageGotoOptions))]
[JsonSerializable(typeof(PageHoverOptions))]
[JsonSerializable(typeof(PageInnerHTMLOptions))]
[JsonSerializable(typeof(PageInnerTextOptions))]
[JsonSerializable(typeof(PageInputValueOptions))]
[JsonSerializable(typeof(PageIsCheckedOptions))]
[JsonSerializable(typeof(PageIsDisabledOptions))]
[JsonSerializable(typeof(PageIsEditableOptions))]
[JsonSerializable(typeof(PageIsEnabledOptions))]
[JsonSerializable(typeof(PageIsHiddenOptions))]
[JsonSerializable(typeof(PageIsVisibleOptions))]
[JsonSerializable(typeof(PageLocatorOptions))]
[JsonSerializable(typeof(PagePdfOptions))]
[JsonSerializable(typeof(PagePressOptions))]
[JsonSerializable(typeof(PageQuerySelectorOptions))]
[JsonSerializable(typeof(PageReloadOptions))]
[JsonSerializable(typeof(PageRouteFromHAROptions))]
[JsonSerializable(typeof(PageRouteOptions))]
[JsonSerializable(typeof(PageRunAndWaitForConsoleMessageOptions))]
[JsonSerializable(typeof(PageRunAndWaitForDownloadOptions))]
[JsonSerializable(typeof(PageRunAndWaitForFileChooserOptions))]
[JsonSerializable(typeof(PageRunAndWaitForNavigationOptions))]
[JsonSerializable(typeof(PageRunAndWaitForPopupOptions))]
[JsonSerializable(typeof(PageRunAndWaitForRequestFinishedOptions))]
[JsonSerializable(typeof(PageRunAndWaitForRequestOptions))]
[JsonSerializable(typeof(PageRunAndWaitForResponseOptions))]
[JsonSerializable(typeof(PageRunAndWaitForWebSocketOptions))]
[JsonSerializable(typeof(PageRunAndWaitForWorkerOptions))]
[JsonSerializable(typeof(PageScreenshotOptions))]
[JsonSerializable(typeof(PageSelectOptionOptions))]
[JsonSerializable(typeof(PageSetCheckedOptions))]
[JsonSerializable(typeof(PageSetContentOptions))]
[JsonSerializable(typeof(PageSetInputFilesOptions))]
[JsonSerializable(typeof(PageTapOptions))]
[JsonSerializable(typeof(PageTextContentOptions))]
[JsonSerializable(typeof(PageTypeOptions))]
[JsonSerializable(typeof(PageUncheckOptions))]
[JsonSerializable(typeof(PageUnrouteAllOptions))]
[JsonSerializable(typeof(PageWaitForConsoleMessageOptions))]
[JsonSerializable(typeof(PageWaitForDownloadOptions))]
[JsonSerializable(typeof(PageWaitForFileChooserOptions))]
[JsonSerializable(typeof(PageWaitForFunctionOptions))]
[JsonSerializable(typeof(PageWaitForLoadStateOptions))]
[JsonSerializable(typeof(PageWaitForNavigationOptions))]
[JsonSerializable(typeof(PageWaitForPopupOptions))]
[JsonSerializable(typeof(PageWaitForRequestFinishedOptions))]
[JsonSerializable(typeof(PageWaitForRequestOptions))]
[JsonSerializable(typeof(PageWaitForResponseOptions))]
[JsonSerializable(typeof(PageWaitForSelectorOptions))]
[JsonSerializable(typeof(PageWaitForURLOptions))]
[JsonSerializable(typeof(PageWaitForWebSocketOptions))]
[JsonSerializable(typeof(PageWaitForWorkerOptions))]
[JsonSerializable(typeof(RouteContinueOptions))]
[JsonSerializable(typeof(RouteFallbackOptions))]
[JsonSerializable(typeof(RouteFetchOptions))]
[JsonSerializable(typeof(RouteFulfillOptions))]
[JsonSerializable(typeof(ScreencastShowActionsOptions))]
[JsonSerializable(typeof(ScreencastShowChapterOptions))]
[JsonSerializable(typeof(ScreencastShowOverlayOptions))]
[JsonSerializable(typeof(ScreencastStartOptions))]
[JsonSerializable(typeof(SelectorsRegisterOptions))]
[JsonSerializable(typeof(TracingGroupOptions))]
[JsonSerializable(typeof(TracingStartChunkOptions))]
[JsonSerializable(typeof(TracingStartHarOptions))]
[JsonSerializable(typeof(TracingStartOptions))]
[JsonSerializable(typeof(TracingStopChunkOptions))]
[JsonSerializable(typeof(TracingStopOptions))]
[JsonSerializable(typeof(WebSocketRouteCloseOptions))]
internal partial class PlaywrightJsonContext : JsonSerializerContext
{
}
