using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlaywrightSharp.ProtocolTypesGenerator
{
    internal static class ProtocolCodeGeneratorUtilities
    {
        public static void AppendAutoGeneratedPrefix(this StringBuilder builder)
            => builder.Append(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

");

        public static void AppendAutoGeneratedSuffix(this StringBuilder builder)
            => builder.AppendLine("#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");
    }
}
