trigger: none # We don't want CI builds, just a manual release process

pool: $(PlaywrightPoolName)

steps:
- task: MicroBuildSigningPlugin@3
  inputs:
    signType: 'test'
    feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Playwright.csproj'
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Playwright.csproj'
    versioningScheme: 'off'