trigger: none # We don't want CI builds, just a manual release process

pool: $(PlaywrightPoolName)

steps:
- task: MicroBuildSigningPlugin@3
  inputs:
    signType: 'test'
    feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'

# We need to download the browsers first, so we can build
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    arguments: '-p $(Build.SourcesDirectory)/src/tools/PlaywrightSharp.Tooling/PlaywrightSharp.Tooling.csproj -- download-drivers --basepath $(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Playwright.csproj'
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Playwright.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nuget'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: MicroBuildCleanup@1