using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.NodeServices;
using Microsoft.Extensions.DependencyInjection;

namespace PlaywrightSharp.ProtocolTypesGenerator.Firefox
{
    internal class FirefoxProtocolTypesGenerator : IProtocolTypesGenerator
    {
        private const string NamespacePrefix = "PlaywrightSharp.Firefox.Protocol";
        private readonly IDictionary<string, string> _knownTypes = new Dictionary<string, string>();
        private readonly IDictionary<string, string> _specialEnumFields = new Dictionary<string, string>
        {
            ["RemoteObjectUnserializableValue.Infinity"] = "Infinity",
            ["RemoteObjectUnserializableValue.-Infinity"] = "NegativeInfinity",
            ["RemoteObjectUnserializableValue.-0"] = "NegativeZero",
            ["RemoteObjectUnserializableValue.NaN"] = "NaN",
            ["SetEmulatedMediaType."] = "Empty",
        };

        public async Task GenerateTypesAsync(RevisionInfo revision)
        {
            string directory = Path.Join("..", "..", "..", "..", "PlaywrightSharp.Firefox", "Protocol");
            string output = Path.Join(directory, "Protocol.Generated.cs");
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string json = await ConvertProtocolJsToJson(revision).ConfigureAwait(false);
            var document = JsonDocument.Parse(json);

            var builder = new StringBuilder();
            var enumBuilder = new StringBuilder();
            builder.AppendAutoGeneratedPrefix();
            foreach (var property in document.RootElement.GetProperty("domains").EnumerateObject())
            {
                builder.AppendLine($"namespace {NamespacePrefix}.{property.Name}");
                builder.AppendLine("{");

                GenerateTypes(builder, enumBuilder, property);
                builder.Append(enumBuilder);
                enumBuilder.Clear();

                builder.AppendLine("}");
            }

            var clip = _knownTypes.Where(pair => pair.Value.Contains("Clip")).ToArray();

            foreach (var property in document.RootElement.GetProperty("domains").EnumerateObject())
            {
                builder.AppendLine($"namespace {NamespacePrefix}.{property.Name}");
                builder.AppendLine("{");

                GenerateEvents(builder, enumBuilder, property);
                GenerateMethods(builder, enumBuilder, property);
                builder.Append(enumBuilder);
                enumBuilder.Clear();

                builder.AppendLine("}");
            }

            builder.AppendAutoGeneratedSuffix();
            await File.WriteAllTextAsync(output, builder.ToString()).ConfigureAwait(false);

            return;
        }

        private void GenerateEvents(StringBuilder builder, StringBuilder enumBuilder, JsonProperty domain)
        {
            foreach (var eventDef in domain.Value.GetProperty("events").EnumerateObject())
            {
                string eventName = eventDef.Name.ToPascalCase();
                builder.Append("internal class ").Append(domain.Name).Append(eventName).AppendLine("FirefoxEvent : IFirefoxEvent");
                builder.AppendLine("{");
                builder.Append("public string InternalName { get; } = \"").Append(domain.Name).Append('.').Append(eventDef.Name).AppendLine("\";");
                foreach (var propertyDef in eventDef.Value.EnumerateObject())
                {
                    if (_knownTypes.TryGetValue(propertyDef.Value.GetRawText(), out string typeName))
                    {
                        builder.AppendLine($"public {typeName} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                        continue;
                    }

                    string csharpType = ConvertJsTypeToCsharp(builder, domain.Name, eventName, propertyDef.Name, propertyDef.Value, enumBuilder);
                    builder.AppendLine($"public {csharpType} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                }

                builder.AppendLine("}");
            }
        }

        private void GenerateMethods(StringBuilder builder, StringBuilder enumBuilder, JsonProperty domain)
        {
            foreach (var methodDef in domain.Value.GetProperty("methods").EnumerateObject())
            {
                string method = methodDef.Name.ToPascalCase();
                builder.AppendLine($"internal class {method}Request : IFirefoxRequest<{method}Response>");
                builder.AppendLine("{");
                builder.AppendLine("[System.Text.Json.Serialization.JsonIgnore]");
                builder.Append("public string Command { get; } = \"").Append(domain.Name).Append('.').Append(methodDef.Name).AppendLine("\";");
                if (methodDef.Value.TryGetProperty("params", out var paramsDef))
                {
                    foreach (var propertyDef in paramsDef.EnumerateObject())
                    {
                        if (_knownTypes.TryGetValue(propertyDef.Value.GetRawText(), out string typeName))
                        {
                            builder.AppendLine($"public {typeName} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                            continue;
                        }

                        string csharpType = ConvertJsTypeToCsharp(builder, domain.Name, methodDef.Name, propertyDef.Name, propertyDef.Value, enumBuilder);
                        builder.AppendLine($"public {csharpType} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                    }
                }

                builder.AppendLine("}");
                builder.AppendLine($"internal class {method}Response : IFirefoxResponse");
                builder.AppendLine("{");

                if (methodDef.Value.TryGetProperty("returns", out var returnesDef))
                {
                    foreach (var propertyDef in returnesDef.EnumerateObject())
                    {
                        if (_knownTypes.TryGetValue(propertyDef.Value.GetRawText(), out string typeName))
                        {
                            builder.AppendLine($"public {typeName} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                            continue;
                        }

                        string csharpType = ConvertJsTypeToCsharp(builder, domain.Name, methodDef.Name, propertyDef.Name, propertyDef.Value, enumBuilder);
                        builder.AppendLine($"public {csharpType} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                    }
                }

                builder.AppendLine("}");
            }
        }

        private void GenerateTypes(StringBuilder builder, StringBuilder enumBuilder, JsonProperty domain)
        {
            foreach (var typeDef in domain.Value.GetProperty("types").EnumerateObject())
            {
                string type = $"{domain.Name}.{typeDef.Name.ToPascalCase()}";
                if (!_knownTypes.TryGetValue(typeDef.Value.GetRawText(), out string typeName))
                {
                    string jsonText = typeDef.Value.GetRawText();
                    string jsonTextNullable = jsonText.Substring(0, jsonText.Length - 1) + ",\"$nullable\":true}";
                    string jsonTextOptional = jsonText.Substring(0, jsonText.Length - 1) + ",\"$optional\":true}";
                    _knownTypes.Add(jsonText, type);
                    _knownTypes.Add(jsonTextNullable, type);
                    _knownTypes.Add(jsonTextOptional, type);
                }

                builder.Append("internal class ").AppendLine(typeDef.Name.ToPascalCase());
                builder.AppendLine("{");
                foreach (var propertyDef in typeDef.Value.EnumerateObject())
                {
                    string csharpType = ConvertJsTypeToCsharp(builder, domain.Name, typeDef.Name, propertyDef.Name, propertyDef.Value, enumBuilder);
                    builder.AppendLine($"public {csharpType} {propertyDef.Name.ToPascalCase()} {{ get; set; }}");
                }

                builder.AppendLine("}");
            }
        }

        /*
        private string ConvertJsTypeToCsharp(StringBuilder builder, string domain, JsonElement obj)
        {
            if (!obj.TryGetProperty("$type", out var typeElement))
            {
                return _knownTypes[obj.GetRawText()];
            }

            string type = typeElement.GetString();
            return type switch
            {
                "string" => "string",
                "boolean" => "bool?",
                "number" => "double?",
                "enum" when _knownTypes.TryGetValue(obj.GetProperty("$values").GetRawText(), out string enumName) => enumName,
                "any" => "JsonElement?",
                "ref" => obj.GetProperty("$ref").GetString(),
                _ => throw new ArgumentOutOfRangeException(nameof(obj), type, $"[{domain}.{obj.ToString()}] invalid array object type")
            };
        }
        */

        private string ConvertJsTypeToCsharp(StringBuilder builder, string domain, string objectName, string name, JsonElement obj, StringBuilder enumBuilder)
        {
            try
            {
                if (!obj.TryGetProperty("$type", out var typeElement))
                {
                    return _knownTypes[obj.GetRawText()];
                }

                string type = typeElement.GetString();
                if (type == "enum" && obj.TryGetProperty("$values", out var values)
                    && !_knownTypes.ContainsKey(values.GetRawText()))
                {
                    string enumName = objectName.ToPascalCase() + name.ToPascalCase();
                    _knownTypes.Add(values.GetRawText(), $"{domain}.{enumName}");
                    enumBuilder.AppendLine($"internal enum {enumName}");
                    enumBuilder.AppendLine("{");
                    foreach (var value in values.EnumerateArray())
                    {
                        if (_specialEnumFields.TryGetValue($"{enumName}.{value.ToString()}", out string fieldName))
                        {
                            enumBuilder.Append(ProtocolCodeGeneratorUtilities.CreateEnumField(value.ToString(), fieldName));
                        }
                        else
                        {
                            enumBuilder.Append(value.ToString().ToEnumField());
                        }

                        enumBuilder.AppendLine(",");
                    }

                    enumBuilder.AppendLine("}");
                }

                return type switch
                {
                    "string" => "string",
                    "boolean" => "bool?",
                    "number" => "double?",
                    "enum" when _knownTypes.TryGetValue(obj.GetProperty("$values").GetRawText(), out string enumName) => enumName,
                    "any" => "JsonElement?",
                    "array" => ConvertJsTypeToCsharp(builder, domain, name, objectName, obj.GetProperty("$items"), enumBuilder) + "[]",
                    "ref" => obj.GetProperty("$ref").GetString(),
                    _ => throw new ArgumentOutOfRangeException(nameof(obj), type, $"[{domain}.{name}] invalid object type")
                };
            }
            catch (Exception e)
            {
                throw new Exception("ERROR", e);
            }
        }

        // INodeServices is deprecated...
#pragma warning disable CS0618 // Type or member is obsolete
        private async Task<string> ConvertProtocolJsToJson(RevisionInfo revision)
        {
            string protocolJs = "chrome/juggler/content/protocol/Protocol.js";
            string zipFile = Path.Combine(Directory.GetParent(revision.ExecutablePath).FullName, "omni.ja");
            using var zip = ZipFile.OpenRead(zipFile);
            using var reader = new StreamReader(zip.GetEntry(protocolJs).Open());
            string js = await reader.ReadToEndAsync().ConfigureAwait(false);

            return await GetNodejs().InvokeExportAsync<string>("Firefox/firefox-protocol.js", "getJson", js).ConfigureAwait(false);
        }

        private INodeServices GetNodejs()
        {
            IServiceCollection services = new ServiceCollection();
            services.AddNodeServices();
            return services.BuildServiceProvider()
                .GetService<INodeServices>();
        }
#pragma warning restore CS0618 // Type or member is obsolete
    }
}
