<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>Microsoft.Playwright.Testing.Platform</Title>
    <PackageId>Microsoft.Playwright.Testing.Platform</PackageId>
    <Description>Microsoft.Testing.Platform configuration support for the Playwright test integrations.</Description>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Microsoft.Playwright.Testing.Platform</RootNamespace>
    <AssemblyName>Microsoft.Playwright.Testing.Platform</AssemblyName>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <Import Project="../Common/Version.props" />
  <Import Project="../Common/SignAssembly.props" />
  <Import Project="../Common/SignFiles.props" />

  <ItemGroup>
    <ProjectReference Include="..\Playwright.TestAdapter\Playwright.TestAdapter.csproj" />
    <PackageReference Include="Microsoft.Testing.Platform" Version="2.4.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudioEng.MicroBuild.Core" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="build\**" Pack="true" PackagePath="buildTransitive" />
    <None Include="build\**" Pack="true" PackagePath="build" />
    <None Include="..\Common\icon.png" Pack="true" PackagePath="icon.png" />
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
