//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace PlaywrightSharp.Firefox.Protocol.Browser
{
}
namespace PlaywrightSharp.Firefox.Protocol.Target
{
}
namespace PlaywrightSharp.Firefox.Protocol.Page
{
    internal class Clip
    {
        public double? x { get; set; }
        public double? y { get; set; }
        public double? width { get; set; }
        public double? height { get; set; }
    }
}
namespace PlaywrightSharp.Firefox.Protocol.Runtime
{
}
namespace PlaywrightSharp.Firefox.Protocol.Network
{
}
namespace PlaywrightSharp.Firefox.Protocol.Accessibility
{
}
namespace PlaywrightSharp.Firefox.Protocol.Browser
{
}
namespace PlaywrightSharp.Firefox.Protocol.Target
{
    internal class TargetattachedToTargetFirefoxEvent
    {
        public string sessionId { get; set; }
        public TargetTargetInfo targetInfo { get; set; }
    }
    internal class TargetdetachedFromTargetFirefoxEvent
    {
        public string sessionId { get; set; }
    }
    internal class TargettargetCreatedFirefoxEvent
    {
        internal enum type
        {
            page,
            browser,
        }
        public Target.type type { get; set; }
        public string targetId { get; set; }
        public string browserContextId { get; set; }
        public string url { get; set; }
        public string openerId { get; set; }
    }
    internal class TargettargetDestroyedFirefoxEvent
    {
        public Target.type type { get; set; }
        public string targetId { get; set; }
        public string browserContextId { get; set; }
        public string url { get; set; }
        public string openerId { get; set; }
    }
    internal class TargettargetInfoChangedFirefoxEvent
    {
        public Target.type type { get; set; }
        public string targetId { get; set; }
        public string browserContextId { get; set; }
        public string url { get; set; }
        public string openerId { get; set; }
    }
}
namespace PlaywrightSharp.Firefox.Protocol.Page
{
    internal class PageeventFiredFirefoxEvent
    {
        public string frameId { get; set; }
        internal enum name
        {
            load,
            DOMContentLoaded,
        }
        public Page.name name { get; set; }
    }
    internal class PageuncaughtErrorFirefoxEvent
    {
        public string frameId { get; set; }
        public string message { get; set; }
        public string stack { get; set; }
    }
    internal class PageframeAttachedFirefoxEvent
    {
        public string frameId { get; set; }
        public string parentFrameId { get; set; }
    }
    internal class PageframeDetachedFirefoxEvent
    {
        public string frameId { get; set; }
    }
    internal class PagenavigationStartedFirefoxEvent
    {
        public string frameId { get; set; }
        public string navigationId { get; set; }
        public string url { get; set; }
    }
    internal class PagenavigationCommittedFirefoxEvent
    {
        public string frameId { get; set; }
        public string navigationId { get; set; }
        public string url { get; set; }
        public string name { get; set; }
    }
    internal class PagenavigationAbortedFirefoxEvent
    {
        public string frameId { get; set; }
        public string navigationId { get; set; }
        public string errorText { get; set; }
    }
    internal class PagesameDocumentNavigationFirefoxEvent
    {
        public string frameId { get; set; }
        public string url { get; set; }
    }
    internal class PagedialogOpenedFirefoxEvent
    {
        public string dialogId { get; set; }
        internal enum type
        {
            prompt,
            alert,
            confirm,
            beforeunload,
        }
        public Page.type type { get; set; }
        public string message { get; set; }
        public string defaultValue { get; set; }
    }
    internal class PagedialogClosedFirefoxEvent
    {
        public string dialogId { get; set; }
    }
    internal class PagebindingCalledFirefoxEvent
    {
        public string executionContextId { get; set; }
        public string name { get; set; }
        public JsonElement? payload { get; set; }
    }
    internal class PagefileChooserOpenedFirefoxEvent
    {
        public string executionContextId { get; set; }
        public RuntimeRemoteObject element { get; set; }
    }
    internal class PageworkerCreatedFirefoxEvent
    {
        public string workerId { get; set; }
        public string frameId { get; set; }
        public string url { get; set; }
    }
    internal class PageworkerDestroyedFirefoxEvent
    {
        public string workerId { get; set; }
    }
    internal class PagedispatchMessageFromWorkerFirefoxEvent
    {
        public string workerId { get; set; }
        public string message { get; set; }
    }
}
namespace PlaywrightSharp.Firefox.Protocol.Runtime
{
    internal class RuntimeexecutionContextCreatedFirefoxEvent
    {
        public string executionContextId { get; set; }
        public JsonElement? auxData { get; set; }
    }
    internal class RuntimeexecutionContextDestroyedFirefoxEvent
    {
        public string executionContextId { get; set; }
    }
    internal class RuntimeconsoleFirefoxEvent
    {
        public string executionContextId { get; set; }
        public RuntimeRemoteObject[] args { get; set; }
        public string type { get; set; }
        public RuntimeScriptLocation location { get; set; }
    }
}
namespace PlaywrightSharp.Firefox.Protocol.Network
{
    internal class NetworkrequestWillBeSentFirefoxEvent
    {
        public string frameId { get; set; }
        public string requestId { get; set; }
        public string redirectedFrom { get; set; }
        public string postData { get; set; }
        public NetworkHTTPHeader[] headers { get; set; }
        public boolean? isIntercepted { get; set; }
        public string url { get; set; }
        public string method { get; set; }
        public string navigationId { get; set; }
        public string cause { get; set; }
    }
    internal class NetworkresponseReceivedFirefoxEvent
    {
        public NetworkSecurityDetails securityDetails { get; set; }
        public string requestId { get; set; }
        public boolean? fromCache { get; set; }
        public string remoteIPAddress { get; set; }
        public double? remotePort { get; set; }
        public double? status { get; set; }
        public string statusText { get; set; }
        public NetworkHTTPHeader[] headers { get; set; }
    }
    internal class NetworkrequestFinishedFirefoxEvent
    {
        public string requestId { get; set; }
    }
    internal class NetworkrequestFailedFirefoxEvent
    {
        public string requestId { get; set; }
        public string errorCode { get; set; }
    }
}
namespace PlaywrightSharp.Firefox.Protocol.Accessibility
{
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
