name: Code Style Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Check formatting
      run: dotnet format ./src/ --verify-no-changes -v:diag
    - name: Download driver
      run: ./build.sh --download-driver
    - name: Build projects (runs .NET analyzers)
      run: dotnet build ./src
