name: Firefox Tests On Win

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build on ${{ matrix.framework }}
    runs-on: windows-latest
    strategy:
      matrix:
#        framework: [netcoreapp3.1, net48]
        framework: [netcoreapp3.1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Run tests
        env:
          PRODUCT: FIREFOX
        run: dotnet test ./src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj --filter Category=firefox -c Debug -f ${{ matrix.framework }}