name: Firefox Tests on Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev xvfb apt-transport-https
          sudo apt-get update
          sudo apt-get install dotnet-sdk-3.1
      - name: Run tests
        env:
          PRODUCT: FIREFOX
        run: xvfb-run --auto-servernum -- bash -c "dotnet test ./src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj --filter Category=firefox -c Debug -f netcoreapp3.1"