name: Tests

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.browser }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [windows-latest, ubuntu-latest, macos-15-large]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Install prerequisites and download drivers
        shell: bash
        run: ./build.sh --download-driver
      - name: Building
        run: dotnet build ./src
      - name: Installing Browsers and dependencies
        run: pwsh src/Playwright/bin/Debug/netstandard2.0/playwright.ps1 install --with-deps ${{ matrix.browser }}
      - name: Running tests
        if: matrix.os != 'ubuntu-latest'
        env:
          BROWSER: ${{ matrix.browser }}
        run: dotnet test ./src/Playwright.Tests/Playwright.Tests.csproj -c Debug -f net8.0 --logger:"console;verbosity=detailed"
      - name: Running tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          BROWSER: ${{ matrix.browser }}
        run: xvfb-run dotnet test ./src/Playwright.Tests/Playwright.Tests.csproj -c Debug -f net8.0 --logger:"console;verbosity=detailed"
