name: Validate NuGet Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 8.0.x
    - name: Download driver
      run: ./build.sh --download-driver
    - name: Validate NuGet packages
      run: dotnet pack ./src/Playwright.sln
