name: Validate NuGet Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Download driver
      run: ./build.sh --download-driver
    - name: Validate NuGet packages
      run: dotnet pack ./src/Playwright.sln
